import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// const robotoBlack = Roboto({
//   weight: "900",
//   subsets: ["latin"],
// })

const roboto = Roboto({
  weight: "500",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className="h-full">
      <body
        className={`antialiased bg-mainThemePrimary ${roboto.className} h-full`}
      >
        <main className="w-full h-full justify-center flex justify-center items-center">
          <div className="md:w-5/6 md:h-5/6 bg-purpleThemePrimary flex shadow-xl">
            <div className="h-full w-24 bg-indigo-500">
            </div>
            <div className="h-full">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
